from django.db import models

class dl(models.Model):
	rto_state=models.CharField(max_length=40)
	rto_office=models.CharField(max_length=200)
	rto_pincode=models.IntegerField() 

	name=models.CharField(max_length=70)
	father_name=models.CharField(max_length=70)
	mother_name=models.CharField(max_length=70)
	adhar_card_no=models.IntegerField() 
	date=models.DateField()
	birth_p=models.CharField(max_length=70)

	email=models.CharField(max_length=70)
	mobile=models.BigIntegerField()
	gender=models.CharField(max_length=70)
	relation=models.CharField(max_length=70)
	age=models.IntegerField() 
	qulification=models.CharField(max_length=70)
	b_group=models.CharField(max_length=70)
	a_mobile=models.BigIntegerField()
	occupation=models.CharField(max_length=70)
	country=models.CharField(max_length=70)
	state=models.CharField(max_length=70)
	city=models.CharField(max_length=70)
	address=models.CharField(max_length=80)
	pincode=models.IntegerField() 
	issues_state=models.CharField(max_length=70)
	issue_date=models.DateField()
	expire_date=models.DateField()
	disablity_yn=models.CharField(max_length=70)
	disablit=models.CharField(max_length=70)
	doner=models.CharField(max_length=70)
	all_yes=models.CharField(max_length=70)
	photo=models.FileField()
	sign=models.FileField()
	document=models.CharField(max_length=70)
	proof=models.CharField(max_length=70)
	doc_no=models.BigIntegerField()
	issue_date_doc=models.DateField()
	issues_by=models.CharField(max_length=70)
	doc_1=models.FileField()
	document_2=models.CharField(max_length=70)
	proof_2=models.CharField(max_length=70)
	doc_no_2=models.BigIntegerField()
	issue_date_2=models.DateField()
	issues_by_2=models.CharField(max_length=70)
	doc_2=models.FileField()
# Create your models here.

# Create your models here.
class registration(models.Model):
	name=models.CharField(max_length=40)
	email=models.CharField(max_length=40)
	password=models.CharField(max_length=40)
	cpassword=models.CharField(max_length=40)
	address=models.CharField(max_length=40)
	mobile=models.BigIntegerField()
	gender=models.CharField(max_length=40)
	state=models.CharField(max_length=40)

